version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - database
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://atexo:pJEYtRDC5Q@mysql_db/atexo_carte_game"

  database:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: WpegHX65yu
      MYSQL_DATABASE: atexo_carte_game
      MYSQL_USER: atexo
      MYSQL_PASSWORD: pJEYtRDC5Q
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:

